version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  golang:
    container_name: golang
    tty: true
    restart: on-failure
    build:
      context: ./golang
    ports:
      - 3000:3000
    volumes:
      - ../:/app
    environment:
      JWT_SECRET: your_jwt_secret_string
volumes:
  mongodata: